### PR TITLE
Initial Symfony 4.0 support

### PR DESCRIPTION
**Pull request by umpirsky**
While we are waiting for https://github.com/ChessCom/chess/pull/24602#issuecomment-374308713...

### CODE REVIEW

**Comment by umpirsky** [comment]
Merged since https://github.com/ChessCom/chess/pull/25194 passed QA.

**Comment by umpirsky** [comment]
@kalifg It's strange that this caused:

```
PHP Fatal error:  Class 'Nelmio\Alice\Loader\Yaml' not found in /www/sites/chess.com/workspace/Pull_Request/src/Chess/WebBundle/Loader/AliceLoader.php on line 9
```

https://ci.devchess.com/job/Pull_Request/84828/consoleFull in https://github.com/ChessCom/chess/pull/25194

@ikonic89 Can it be some CI specific issue? It works locally and the file is there.

**Comment by ikonic89** [comment]
No idea, tbh.

**Comment by kalifg** [comment]
It happens to me locally.  The steps I follow:
1. Checkout the `SS/CV-60699-Symfony-4-0-Upgrade` branch
2. Run `bin/c backend -v '--memory=1250M'`

I'll dig in and see what I can find.  It might be related to the Alice fork bump that it's installing.

**Comment by kalifg** [comment]
If you step through the autoloader code you can see that no references to the Alice classes are stored for either PSR0 or PSR4, and it's not on the include path so the autoloader returns false.

Is it possible that SF4 changed the autoloader in a way that we need to update the Alice fork to support it?

**Comment by kalifg** [comment]
Some time during the composer process, it writes the file `vendor/composer/installed.json`.  When you run `php composer.phar dump-autoload` it reads the list of installed packages from that.  This file does not contain Alice on my system, and so Alice never makes it to the autoloader.

I'm still attempting to isolate the creation of this file to see why it doesn't make it into there.

**Comment by kalifg** [comment]
And here's the crazy thing.  I re-ran composer and it installed Alice and everything looks fine.

**Comment by kalifg** [comment]
I am able to reproduce this error by doing the following:

1.  Check out `develop`
2. Run `c composer`
3. Check out `SS/CV-60699-Symfony-4-0-Upgrade`
4. Run `c composer`. You will see
```
      - Removing nelmio/alice (dev-master 581ae45)
      - Installing nelmio/alice (dev-master 534d232): Loading from cache
```
5. Run `php -d memory_limit=1250M app/console --env=test --ansi -vvv --no-debug alice:fixtures:load --no-interaction --em=root --quiet`.  You will then get the error:
```
PHP Fatal error:  Class 'Nelmio\Alice\Loader\Yaml' not found in /www/sites/chess.com/current/src/Chess/WebBundle/Loader/AliceLoader.php on line 9

Fatal error: Class 'Nelmio\Alice\Loader\Yaml' not found in /www/sites/chess.com/current/src/Chess/WebBundle/Loader/AliceLoader.php on line 9
```

Then if you:
1. Run `c composer`. You will see:
```
      - Installing nelmio/alice (dev-master 534d232): Loading from cache
```
2. `php -d memory_limit=1250M app/console --env=test --ansi -vvv --no-debug alice:fixtures:load --no-interaction --em=root --quiet`.  Everything now works as normal.

I think there is some issue with composer.  Attempting to trace an install is difficult because of how much everything is slowed down.  I'll see what I can do, but maybe in the mean time someone can come up with a work-around?  Should we just add a second run of `composer` to our tasks?

**Comment by kalifg** [comment]
After ChessCom/chess#26529 is merged into develop I will re-run CI on ChessCom/chess#25194

**Pull request merged**
